Error: Verification failed in function 'test24'/'foo':
Tail calls can only be done in functions with standard calling convention.

The invalid instruction was (index 0 in block 'entry'):
'i' = call.tail ('test24'/'foo')
